[project]
name = "adran"
version = "1.0.2"
description = "Hierarchical expansion of markdown formatted text."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Rust",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[build-system]
requires = ["maturin>=1.3,<2"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
name = "adran"
python-source = "src"
